# Generated by Django 4.2.23 on 2025-08-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'profesiones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('profesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.profesion')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
